
language: python

cache: pip

python:
  - "3.7"

before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov-report term-missing --cov=app tests/
after_success:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY_SECRET
  region: $AWS_REGION
  app: $AWS_EB_APPLICATION
  env: $AWS_EB_ENVIRONMENT
  bucket_name: $AWS_EB_S3_BUCKET