
language: python

cache: pip

python:
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov-report term-missing --cov=app tests/
after_success:
  - coveralls