version: "3.3"

services:
  web:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment:
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      - SERVER_NAME=${SERVER_NAME?Variable not set}
      - PROJECT_NAME=${PROJECT_NAME?Variable not set}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS?Variable not set}
      - ZOHO_REDIRECT_URI=${ZOHO_REDIRECT_URI?Variable not set}
      - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID?Variable not set}
      - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET?Variable not set}
      - ZOHO_ACCESS_TOKEN=${ZOHO_ACCESS_TOKEN?Variable not set}
      - ZOHO_REFRESH_TOKEN=${ZOHO_REFRESH_TOKEN?Variable not set}
      - ZOHO_AUTHORIZATION_CODE=${ZOHO_AUTHORIZATION_CODE?Variable not set}
      - ZOHO_OAUTH_SCOPES=${ZOHO_OAUTH_SCOPES?Variable not set}
      - ZOHO_DEPARTMENTS=${ZOHO_DEPARTMENTS?Variable not set}